### ISSUE TITLE
Triggering snippets in html with {% and {{

### ISSUE THREAD

**Issue by danihodovic** [neoclide/coc-html#13]
Often when writing html files with templates I'd like to complete snippets starting with `{%` or `{{`. Is it possible to enable this in CoC?

For example in Django templates I want to trigger `{%` to expand into `{% url "some-url" %}`

**Comment by chemzqm** [comment]
No, you have to snippet plugin and trigger is manually (most likely).
They're not part of html.

**Comment by danihodovic** [comment]
Any idea on how to trigger it manually for html files?

**Comment by chemzqm** [comment]
No, can't help.
