### ISSUE TITLE
Add linter support

### ISSUE THREAD

**Issue by jmolero** [neoclide/coc-html#14]
Thank for making this extension.

I tried the formatter and it works great but it stopped working after adding `htmltidy` as a `coc-diagnostic` linter.

Would it be possible to have both working at the same time? Or maybe `coc-html` should provide a linter instead of having to set it "manually" using `coc-diagnostic`.

**Comment by chemzqm** [comment]
It has limited lint support, it won't use tools like `htmltidy`

**Comment by jmolero** [comment]
Ok. Thanks anyway.
