### ISSUE TITLE
Problems with xhtml

### ISSUE THREAD

**Issue by hsequeda** [neoclide/coc-html#23]
I was trying to use the coc-html plugin with an xhtml file and it didn't work for me, I tried to add "xhtml" to the html.filetype variable in cocConfig, but nothing at all.

**Comment by yaegassy** [comment]
@stdevHsequeda 

Add `g:coc_filetype_map` setting to your `.vimrc` or `init.vim` and try it out.

```vim
let g:coc_filetype_map = {
  \ 'xhtml': 'html',
  \ }
```

**Comment by chemzqm** [comment]
It's not designed to work with xhtml filetype, you have to use `g:coc_filetype_map`.
