### ISSUE TITLE
Issue completing some closing tags and file paths

### ISSUE THREAD

**Issue by taglia** [neoclide/coc-html#26]
I have an issue with the completion of some closing tags and file paths. For example, if I try to complete `</em>` or `</center>`, an extra `</` at the end; also, hitting `tab` to complete does not work, I need to move the cursor down and use `Enter`. The same thing happens with `</center>` and other tags. When I try to complete file paths, the new path component is often added on top of the `/` separator.

I have recorded a quick screencast to show the issue. I have several other plugins installed, but I have tried leaving CoC only, and the behavior is the same. I can't find anything else in my config files that could interfere either.

![coc-html-issue](https://user-images.githubusercontent.com/612306/96359112-747fa180-1141-11eb-8843-1eee324020de.gif)

**Comment by chemzqm** [comment]
Could be bug of coc.nvim.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
You have to use `coc#_select_confirm` for that case.
