### ISSUE TITLE
How to change the HTML tag showmatch colors ?

### ISSUE THREAD

**Issue by xinyu-io** [neoclide/coc-html#29]
Below will let the font of the matching tag turn to white:
```
set showmatch
hi MatchParen ctermfg=white guifg=white
```
![image](https://user-images.githubusercontent.com/32320149/101988200-1c919100-3cd3-11eb-9212-676065ba1d3c.png)

How to change the colors of the matching tags of HTML?

![image](https://user-images.githubusercontent.com/32320149/101988238-4e0a5c80-3cd3-11eb-9adf-25cea14b9d08.png)

**Comment by chemzqm** [comment]
Don't know, not related to this extension.

**Comment by xinyu-io** [comment]
I think they have a relation.
Because coc-html has the power that HTML tags showmatch.

**Comment by chemzqm** [comment]
It's not
