### ISSUE TITLE
CocInstall coc-html not working

### ISSUE THREAD

**Issue by Antonio-Bennett** [neoclide/coc-html#34]
Hello, I would like to install this extension but it doesn't work. The report says; 
![image](https://user-images.githubusercontent.com/31296212/108055040-6ec99800-701d-11eb-92b6-7294ff81cc69.png)

**Comment by chemzqm** [comment]
It's already fixed, please upgrade to the latest release branch of coc.nvim.

**Comment by Antonio-Bennett** [comment]
Thanks!
