### ISSUE TITLE
Complete CSS/SCSS classes?

### ISSUE THREAD

**Issue by mrjones2014** [neoclide/coc-html#36]
Is there a way to specify where my stylesheets are located and have coc-html complete the CSS classes from my stylesheets while writing HTML?

**Comment by yaegassy** [comment]
@mrjones2014 Hi, Try using `coc-html-css-support`. https://github.com/yaegassy/coc-html-css-support

**Comment by mrjones2014** [comment]
@yaegassy looks awesome! does it support sass/scss stylesheets?

**Comment by yaegassy** [comment]
sass/scss are not supported. To set the final generated css file.
