### ISSUE TITLE
Blade syntax highlighting not working

### ISSUE THREAD

**Issue by thorlucas** [neoclide/coc-html#37]
Setting the filetype to `blade` removes all syntax highlighting.

**Comment by thorlucas** [comment]
As a matter of fact, it seems that even though the `blade` is in the filetypes configuration, `coc-html` is not being activated for the blade filetype.

**Comment by chemzqm** [comment]
You have to use syntax highlight plugin for blade

**Comment by thorlucas** [comment]
> You have to use syntax highlight plugin for blade

This invalidates the use of `coc-html` altogether -- using a blade syntax highlighting plugin such as `vim-blade` overrides all the features `coc-html` provide such as formatting etc.
