### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by hugbubby** [neoclide/coc-html#38]
Running :CocInstall coc-html doesn't do anything. I see no linting, autocompletion, etc. Plugin is enabled in :CocList and :CocInfo shows no errors. This happens for one out of every two plugins I try to install unfortunately.

**Comment by hugbubby** [comment]
Please add xhtml to filetypes.

**Comment by edwarmv** [comment]
hi, you can add your filetype to ```html.filetypes``` option in your coc-settings.json file

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map`
