### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by lucasvianav** [neoclide/coc-html#40]
I'm not getting any syntax highlighting for HTML files. 

I don't know if this is how it should be and haven't found any information about it, but I was expecting it to be like [tsserver](https://github.com/neoclide/coc-tsserver) does for React files - is there any to make the syntax highlighting look more like that?

HTML:
![HTML File Screenshot](https://user-images.githubusercontent.com/23108450/122649770-e875ad80-d105-11eb-8d6d-141fcafc14d7.png)

React:
![React File Screenshot](https://user-images.githubusercontent.com/23108450/122649881-7a7db600-d106-11eb-91e0-98bb02c3cddd.png)

**Comment by chemzqm** [comment]
coc-html doesn't provide any syntax highlighting, use syntax plugin.
