### ISSUE TITLE
i don't know why there is a underline under text

### ISSUE THREAD

**Issue by goiw111** [neoclide/coc-html#50]
![Screenshot from 2022-02-21 22-59-48](https://user-images.githubusercontent.com/32710356/155031310-0d312a27-a9bb-485f-a12d-876646905d8e.png)

**Comment by chemzqm** [comment]
Try :CocRestart to see if it's cleared

**Comment by goiw111** [comment]
no, it didn't!

**Comment by goiw111** [comment]
thank you for your interesting , I'll try to get used to it
