### ISSUE TITLE
Configuring indentantion of formatter

### ISSUE THREAD

**Issue by jannes** [neoclide/coc-html#51]
I couldn't find an option to configure the indent (to 2 spaces), am I missing something or is that not supported? If not supported yet, I think that would be a great addition:)

**Comment by chemzqm** [comment]
It uses vim's option

**Comment by jannes** [comment]
Thanks, that makes sense!
For anyone who's looking to do the same, here's how I changed the indent for HTML only:
```
autocmd Filetype html setlocal shiftwidth=2 softtabstop=2 expandtab
```
