### ISSUE TITLE
Settings don't work?

### ISSUE THREAD

**Issue by seriiserii825** [neoclide/coc-html#53]
Hi, thanks for plugin. 
I can't understand, why settings from coc-settings.json don't work.

```js
  "html.format.wrapLineLength": 400,
  "html.completion.attributeDefaultValue": "singlequotes"
```

Wrap line by default has 120 symbols, but i want more, 400. 
But settings don't work.
![Alt text](https://i.imgur.com/YzmTaej.png)
Thanks.

**Comment by chemzqm** [comment]
You could be use something other than coc-html to format, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
