### ISSUE TITLE
Passing arguments to Tidy?

### ISSUE THREAD

**Issue by xiumingzhang** [neoclide/coc-html#54]
Good work! If I'm not wrong, coc-html implicitly runs Tidy on the buffer, giving error and warning hints for the current buffer content.

I often use Tidy to auto-format my HTML code with

```bash
tidy -m /path/to/my.html
```

Is there a way to pass `-m` to Tidy so that my buffer gets auto-formatted on every buffer write? Thanks.

#### Update

Achieved this with neomake by adding:

```vim
let g:neomake_html_enabled_makers = ['tidy']
let g:neomake_html_tidy_maker = { 'args': ['-modify'] }
```

to my neovim configuration. But this, together with coc-html, will run Tidy twice, right? Doesn't sound optimal to me.

**Comment by chemzqm** [comment]
It can't use tidy, vscode-html-languageservice is used
