### ISSUE TITLE
Overload on Ram during installation

### ISSUE THREAD

**Issue by mahmood601** [neoclide/coc-html#56]
I have tried to install coc-html. in each attempt it failed and nvim stopped suddenly
OS : termux / aarch 64 / Ram 4

**Comment by chemzqm** [comment]
The typescript dependency is a litter big(~ 70M),  see `:h coc-config-npm-binPath` for a different package manager.

**Comment by chemzqm** [comment]
Free some memory from your system should help.

**Comment by mahmood601** [comment]
The Random memory reachs to highest value then turn back to 1 GB

**Comment by chemzqm** [comment]
Should be something wrong with your npm, you can isntall from source code https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension
