### ISSUE TITLE
Freemarker: coc-html overrides coc-snippets

### ISSUE THREAD

**Issue by caneta** [neoclide/coc-html#6]
Hi. I've succesfully installed coc-snippets, which I use for my [freemarker](https://freemarker.apache.org/) templates:

![snippets-freemarker](https://user-images.githubusercontent.com/4066659/67748659-b3e24900-fa2b-11e9-8d05-5f00daed8259.png)
After that, I've installed coc-html and configured it to use in my templates:
```
let g:coc_filetype_map = {
\ 'freemarker': 'html',
\ }
```
But that has overridden my snippets, only html autocompletion is now active:

![html-freemarker](https://user-images.githubusercontent.com/4066659/67748783-ff94f280-fa2b-11e9-8942-719550ca7eab.png)
Am I missing some other configuration to have both autocomplete suggestions?
Thank you.

**Comment by chemzqm** [comment]
Use `snippets.extends` https://github.com/neoclide/coc-snippets and remove that filetype map.

**Comment by caneta** [comment]
That worked like a charm, thanks @chemzqm!
I've removed the filetype map and added the following to my _~/.config/nvim/coc-settings.json_: `{"snippets.extends":{"freemarker":["html"]}}`; here the result:

![both](https://user-images.githubusercontent.com/4066659/67751376-4cc79300-fa31-11e9-9a64-c978ba33a151.png)
